//
//  ViewModel.swift
//  BobyAl-CaseStudy
//
//  Created by Reşat Kut on 24.04.2023.
//

import Foundation
import OpenAISwift
import SwiftUI


class ViewModel:ObservableObject{
    @Published var Promt = [promtModel]()
    @Published var PromtAi = [String]()
    
    @Published var ResTap = false
    @Published var PatTap = false
    @Published var ShaTap = false
    @Published var onBoarding = true

    
    
    @Published var trait = ""
    
    
    private var client:OpenAISwift?
    
    init(){
        //self.SetUp()
    }
    
    func SetUp(){
        client = OpenAISwift(authToken: "YOUR_API_KEY")
    }
    
    func generateStoryAiMessage(age:Int,trait:String,message:String){
       
        generateStoryAi(message: message){ response in
            DispatchQueue.main.async {
                self.PromtAi.append(response)
            }
        }
        
    }
    private func generateStoryAi(message:String,completion: @escaping (String) -> Void){
        client?.sendCompletion(with: message,maxTokens: 500, completionHandler: { result in
            switch result{
            case.success(let model):
                let messageOut = model.choices?.first?.text ?? "Error"
                completion(messageOut)
            case.failure:
                break
            }
        })
    }
    func generateStory(age:Int,trait:String){
        Promt = ViewModel.promtData.filter{($0.age == age && $0.trait == trait)}
    }
    
}


extension ViewModel{
    static var promtData:[promtModel]{
        [
            promtModel(age: 3, trait:"Patience,", story: "Once upon a time, in a beautiful forest, there lived a little rabbit named Rosie. Rosie loved to hop around and explore her surroundings, but sometimes she found it hard to be patient.One day, Rosie was out hopping around when she saw a beautiful flower in the distance. She wanted to reach it, but the flower was on the other side of a small pond. Rosie didn't know how to swim, and she was getting impatient.That's when a wise old turtle appeared. The turtle saw Rosie's impatience and asked her what was wrong. Rosie told the turtle that she wanted to reach the flower, but she couldn't because she didn't know how to swim.The turtle smiled and said,Patience is the key, my dear Rosie. You need to be patient and wait for the right moment.Rosie was confused, but she decided to take the turtle's advice. She sat down by the pond and watched the flower. She waited and waited, and eventually, a gust of wind blew the flower towards her side of the pond. Rosie was so happy and excited that she forgot all about her impatience.The turtle came over to Rosie and congratulated her on being patient. He explained that being patient means waiting for the right moment and not giving up when things get tough.From that day on, Rosie tried to be more patient in everything she did. She realized that being patient made her feel more relaxed and less stressed. She also found that she was able to enjoy her surroundings more when she took her time and didn't rush.Whenever Rosie felt like she was starting to lose her patience, she remembered the wise old turtle's words and took a deep breath. She knew that with patience, she could accomplish anything she set her mind to.And so, Rosie lived happily ever after, hopping around and being patient in all that she did."),
            
            promtModel(age: 3, trait: "Sharing,", story: "Once upon a time, in a magical kingdom, there lived a little girl named Emma. Emma loved to play with her toys, but sometimes she found it hard to share.One day, Emma's friends came over to play, and they all brought their favorite toys. Emma was excited to play with her friends, but she didn't want to share her toys. She thought her toys were the best, and she wanted to keep them all to herself.But as the day went on, Emma noticed that her friends were having more fun playing with each other's toys than with hers. Emma realized that sharing her toys could be fun too. Emma's friends started to share their toys with her, and Emma was amazed at how much more fun they were having. She wanted to share her toys too, but she didn't know how.That's when a wise old owl appeared. The owl saw Emma's struggle and asked her what was wrong. Emma told the owl that she wanted to share her toys, but she didn't know how.The owl smiled and said, Sharing is the key, my dear Emma. You need to be willing to let others play with your toys and be happy when they do.Emma was confused, but she decided to take the owl's advice. She chose her favorite toy, a stuffed bear, and gave it to her friend to play with. Emma felt a little nervous at first, but when she saw how happy her friend was, she felt happy too. From that day on, Emma tried to share her toys more often. She realized that sharing made her feel good and that it made her friendships stronger. She also found that her friends were more willing to share their toys with her when she shared hers with them."),
            
            promtModel(age: 3,trait: "Respect,", story: "Once upon a time, in a beautiful forest, there lived a little fox named Max. Max loved to play and explore, but sometimes he found it hard to be respectful. One day, Max was out exploring the forest when he came across a group of animals. The animals were having a meeting to discuss important issues, but Max didn't pay attention. He ran around and made loud noises, disrupting the meeting.The animals were annoyed with Max and asked him to leave. Max didn't understand why they were upset and felt sad that he couldn't join the meeting.That's when a wise old deer appeared. The deer saw Max's behavior and asked him what was wrong. Max told the deer that he wanted to be a part of the meeting, but he didn't know how to be respectful.The deer smiled and said, Respect is the key, my dear Max. You need to be respectful of others and listen to their thoughts and opinions. Max was confused, but he decided to take the deer's advice. He went back to the animals and apologized for his behavior. He asked if he could join the meeting and promised to be respectful.The animals were impressed with Max's apology, and they allowed him to join the meeting. Max listened carefully to what everyone had to say, and he realized that he could learn a lot from the other animals.From that day on, Max tried to be more respectful in everything he did. He realized that being respectful made him feel more appreciated and that he learned more when he listened to others.Whenever Max felt like he wasn't being respectful, he remembered the wise old deer's words and took a deep breath. He knew that respect was an important part of being a good friend.And so, Max lived happily ever after, exploring the forest and being respectful to all the animals he met."),
            
            promtModel(age: 3,trait: "Patience,Sharing,", story: "Once upon a time, in a magical land far away, there lived a little girl named Lily. Lily loved to play with her toys, but sometimes she found it hard to be patient and share her toys with others.One day, Lily's friends came over to play, and they all brought their favorite toys. Lily was excited to play with her friends, but she didn't want to share her toys. She thought her toys were the best, and she wanted to keep them all to herself. But as the day went on, Lily noticed that her friends were having more fun playing with each other's toys than with hers. Lily realized that sharing her toys could be fun too.Lily's friends started to share their toys with her, and Lily was amazed at how much more fun they were having. She wanted to share her toys too, but she didn't know how.That's when a wise old owl appeared. The owl saw Lily's struggle and asked her what was wrong. Lily told the owl that she wanted to share her toys, but she didn't know how.The owl smiled and said, Patience and sharing are the keys, my dear Lily. You need to be willing to wait your turn and be happy when others play with your toys.Lily was confused, but she decided to take the owl's advice. She chose her favorite toy, a stuffed bear, and gave it to her friend to play with. Lily felt a little nervous at first, but when she saw how happy her friend was, she felt happy too.From that day on, Lily tried to share her toys more often. She realized that sharing made her feel good and that it made her friendships stronger. She also found that her friends were more willing to share their toys with her when she shared hers with them.Whenever Lily felt like she didn't want to share, she remembered the wise old owl's words and took a deep breath. She knew that patience and sharing were important parts of being a good friend.And so, Lily lived happily ever after, playing with her friends and sharing her toys with them. She learned that patience and sharing were the keys to having fun and making friendships stronger."),
            
            promtModel(age: 3,trait: "Respect,Patience,", story: "Once upon a time, in a magical kingdom, there lived a little boy named Oliver. Oliver loved to play and explore, but sometimes he found it hard to be patient and respectful.One day, Oliver was out playing with his friends when he noticed an older gentleman walking by. Oliver's friends started to make fun of the man, but Oliver felt uneasy. He knew that it wasn't respectful to make fun of someone just because they were different.Oliver decided to speak up and tell his friends to stop. But his friends didn't listen and continued to make fun of the man. Oliver felt sad and didn't know what to do.That's when a wise old owl appeared. The owl saw Oliver's struggle and asked him what was wrong. Oliver told the owl that he wanted to be respectful, but his friends were being mean.The owl smiled and said, Patience and respect are the keys, my dear Oliver. You need to be patient with your friends and respectfully explain why it's important to be kind to others.Oliver was confused, but he decided to take the owl's advice. He waited until his friends were finished making fun of the man, and then he respectfully explained why it wasn't right. He told them that it was important to be kind to others, no matter how different they were.Oliver's friends were surprised, but they listened to what he had to say. They realized that Oliver was right and apologized to the man. Oliver felt happy that he was able to make a difference and that he stood up for what was right.From that day on, Oliver tried to be more patient and respectful in everything he did. He realized that being patient made him feel more relaxed and less stressed. He also found that being respectful to others made him feel good inside. Whenever Oliver felt like he was starting to lose his patience or respect, he remembered the wise old owl's words and took a deep breath. He knew that patience and respect were important values to have.And so, Oliver lived happily ever after, playing with his friends and respecting others. He learned that patience and respect were the keys to being a good person and that standing up for what was right was always worth it."),
            
            promtModel(age: 3, trait: "Respect,Patience,Sharing,", story: "Once upon a time, in a faraway land, there lived a little girl named Lily. Lily was very kind, but she was not very patient. She would often get upset when things did not happen as quickly as she wanted them to.One day, Lily went to the park to play with her friends. As she was playing, she noticed a little boy who was having trouble climbing up the ladder to the slide. The little boy was getting frustrated because he couldn't climb up as fast as the other kids.Lily could see that the little boy needed help, so she walked over to him and asked if he needed help. The little boy nodded his head, and Lily offered to help him climb up the ladder. She patiently guided him step by step until he made it to the top of the slide. The little boy was very happy and thanked Lily for her help.As Lily was walking away, she heard her friends calling her to come and play with them. But Lily knew that the little boy still needed help, so she stayed with him and played with him until he was ready to go home.Lily's friends were a bit annoyed with her for not playing with them, but Lily explained that it was important to be patient and to help others when they needed it. She told her friends that being respectful and sharing were important values to have, and that they should try to be patient and kind like her.From that day on, Lily's friends started to understand the importance of patience, respect, and sharing. They started to help each other more often and to be more patient when things did not go as planned.And as for Lily, she learned that being patient and helping others brought her more joy and happiness than anything else in the world. She realized that being kind and respectful to others made her a better person, and she continued to live her life by these values every day."),
            
            promtModel(age: 3,trait: "Respect,Sharing,", story: "Once upon a time, in a beautiful meadow, there lived a little girl named Lucy. Lucy loved to play with her toys, but sometimes she found it hard to share and be respectful.One day, Lucy was playing with her favorite doll when she saw her friend Lily walking by. Lily looked sad, and Lucy wanted to help her feel better. She ran over to Lily and asked her what was wrong.Lily told Lucy that she was feeling lonely because her friends were playing without her. Lucy knew how Lily felt and wanted to make her feel better. She asked Lily to join her and play with her doll.Lucy's other friends came over to join in the fun, and Lucy shared her toys with everyone. They all had a great time playing together and laughing.That's when a wise old owl appeared. The owl saw Lucy's kindness and asked her what she was doing. Lucy told the owl that she was sharing her toys with her friends to make them happy.The owl smiled and said, Sharing and respect are the keys, my dear Lucy. You need to be respectful of your friends and share your toys with them. This will make your friendships stronger and more meaningful.Lucy was confused, but she decided to take the owl's advice. She started to share her toys more often and treated her friends with respect. She listened to what they had to say and tried to help them whenever they needed it.Lucy found that when she shared her toys and respected her friends, they were more willing to do the same for her. She realized that being kind and respectful to others made her feel good inside and made her friendships stronger.Whenever Lucy felt like she didn't want to share or be respectful, she remembered the wise old owl's words and took a deep breath. She knew that sharing and respect were important values to have.And so, Lucy lived happily ever after, playing with her friends and sharing her toys with them. She learned that sharing and respect were the keys to having fun and making friendships stronger."),
            
            promtModel(age: 4,trait: "Patience,", story: "Once upon a time, in a magical land far away, there lived a young boy named Jack. Jack loved to play and explore, but sometimes he found it hard to be patient.One day, Jack was out exploring the forest when he came across a beautiful butterfly. He watched as it fluttered its wings, and he wanted to catch it and hold it in his hand. But every time he tried to catch it, the butterfly flew away.Jack tried again and again, but each time he failed. He was starting to get frustrated and upset. That's when an old wise owl appeared.The owl saw Jack's frustration and asked him what was wrong. Jack told the owl that he wanted to catch the butterfly but couldn't because it kept flying away. The owl smiled and said, Patience is the key, my dear Jack. You need to be patient and wait for the right moment.Jack was confused, but he decided to take the owl's advice. He sat down next to the butterfly and watched it closely. He waited and waited, and finally, the butterfly landed on his finger.Jack was so excited that he almost forgot to be patient. But he remembered the owl's words and stayed still, watching the butterfly. After a few moments, the butterfly flew away, but Jack was happy because he had learned the value of patience.From that day on, Jack tried to be more patient in everything he did. He realized that being patient made him feel more relaxed and less stressed. He also found that he was able to accomplish more when he took his time and didn't rush.Whenever Jack felt like he was starting to lose his patience, he remembered the wise owl's words and took a deep breath. He knew that with patience, he could achieve anything he set his mind to.And so, Jack lived happily ever after, exploring the magical forest and being patient in all that he did."),
            
            promtModel( age: 4,trait:"Sharing,", story: "Once upon a time, in a beautiful village, there lived a little boy named James. James loved to play and explore, but sometimes he found it hard to share his toys with others.One day, James was playing with his favorite toy car when his friend Alex came over. Alex asked if he could play with the car too, but James didn't want to share. He thought that his car was the best, and he wanted to keep it all to himself.Alex felt sad and left to play on his own. James felt a little guilty but didn't know how to make it right.That's when a wise old owl appeared. The owl saw James's struggle and asked him what was wrong. James told the owl that he wanted to share his toys, but he didn't know how.The owl smiled and said,Sharing is the key, my dear James. You need to be willing to let others play with your toys and be happy when they do. This will make your friendships stronger and more meaningful.James was confused, but he decided to take the owl's advice. He went to find Alex and asked him to come back and play with him. James let Alex play with his favorite toy car, and they had a great time playing together.From that day on, James tried to share his toys more often. He realized that sharing made him feel good inside and that it made his friendships stronger. He also found that his friends were more willing to share their toys with him when he shared his with them.Whenever James felt like he didn't want to share, he remembered the wise old owl's words and took a deep breath. He knew that sharing was an important part of being a good friend.And so, James lived happily ever after, playing with his friends and sharing his toys with them. He learned that sharing was the key to having fun and making friendships stronger."),
            
            promtModel( age: 4,trait: "Respect,", story: "Once upon a time, in a peaceful town, there lived a little girl named Sarah. Sarah loved to play and have fun, but sometimes she found it hard to be respectful towards others.One day, Sarah was playing at the park when she saw an older man walking by. The man looked lost, and Sarah wanted to help him. She ran over to him and asked if he needed any help.The man appreciated Sarah's kindness and asked for directions to the nearest store. Sarah pointed him in the right direction and wished him good luck.That's when a wise old owl appeared. The owl saw Sarah's kindness and asked her what she was doing. Sarah told the owl that she was helping the man because she wanted to be respectful towards him.The owl smiled and said, Respect is the key, my dear Sarah. You need to be respectful towards others, no matter how different they are. This will make them feel appreciated and valued.Sarah was confused, but she decided to take the owl's advice. She started to treat everyone with respect and listened to what they had to say. She realized that being respectful towards others made her feel good inside and that it made her relationships stronger. Whenever Sarah felt like she wasn't being respectful, she remembered the wise old owl's words and took a deep breath. She knew that respect was an important value to have.And so, Sarah lived happily ever after, playing with her friends and treating everyone with respect. She learned that respect was the key to having fun and making relationships stronger."),
            
            promtModel(age: 4,trait: "Patience,Sharing,", story: "Once upon a time, in a lively town, there lived a little boy named Jack. Jack loved to play and have fun, but sometimes he found it hard to be patient and share his toys with others.One day, Jack's friends came over to play, and they all brought their favorite toys. Jack was excited to play with his friends, but he didn't want to share his toys. He thought his toys were the best, and he wanted to keep them all to himself.But as the day went on, Jack noticed that his friends were having more fun playing with each other's toys than with his. Jack realized that sharing his toys could be fun too.Jack's friends started to share their toys with him, and Jack was amazed at how much more fun they were having. He wanted to share his toys too, but he didn't know how.That's when a wise old owl appeared. The owl saw Jack's struggle and asked him what was wrong. Jack told the owl that he wanted to share his toys, but he didn't know how.The owl smiled and said, Patience and sharing are the keys, my dear Jack. You need to be willing to wait your turn and be happy when others play with your toys. This will make your friendships stronger and more meaningful.Jack was confused, but he decided to take the owl's advice. He chose his favorite toy, a toy truck, and gave it to his friend to play with. Jack felt a little nervous at first, but when he saw how happy his friend was, he felt happy too. From that day on, Jack tried to share his toys more often. He realized that sharing made him feel good and that it made his friendships stronger. He also found that his friends were more willing to share their toys with him when he shared his with them.Whenever Jack felt like he didn't want to share, he remembered the wise old owl's words and took a deep breath. He knew that patience and sharing were important values to have.And so, Jack lived happily ever after, playing with his friends and sharing his toys with them. He learned that patience and sharing were the keys to having fun and making friendships stronger."),
            
            promtModel(age: 4,trait: "Respect,Patience,", story: "Once upon a time, in a peaceful village, there lived a little girl named Emma. Emma loved to play and have fun, but sometimes she found it hard to be patient and respectful towards others.One day, Emma was playing with her friends at the park when they saw a group of older kids playing soccer. Emma and her friends wanted to join in, but the older kids didn't want them to play. They told Emma and her friends to leave.Emma felt sad and didn't know what to do. But she remembered the wise words of her parents who had told her to always be patient and respectful towards others.Emma decided to wait patiently and respectfully for the older kids to finish playing. She sat down and watched the game, cheering for both teams.The older kids noticed how patient and respectful Emma was and were impressed. They invited Emma and her friends to play with them after the game.Emma and her friends were thrilled and had a great time playing soccer with the older kids. Emma learned that being patient and respectful towards others could make a difference and that it could help her make new friends.From that day on, Emma tried to be more patient and respectful towards everyone she met. She realized that being patient made her feel more relaxed and less stressed. She also found that being respectful towards others made her feel good inside. Whenever Emma felt like she wasn't being patient or respectful, she remembered the wise words of her parents and took a deep breath. She knew that patience and respect were important values to have.And so, Emma lived happily ever after, playing with her friends and treating everyone with patience and respect. She learned that patience and respect were the keys to making new friends and having fun."),
            
            promtModel( age: 4,trait: "Respect,Patience,Sharing,", story: "Once upon a time, in a charming town, there lived a little girl named Sophie. Sophie loved to play and have fun, but sometimes she found it hard to be patient, share her toys, and be respectful towards others.One day, Sophie's friends came over to play, and they all brought their favorite toys. Sophie was excited to play with her friends, but she didn't want to share her toys. She thought her toys were the best, and she wanted to keep them all to herself.But as the day went on, Sophie noticed that her friends were having more fun playing with each other's toys than with hers. Sophie realized that sharing her toys could be fun too.Sophie's friends started to share their toys with her, and Sophie was amazed at how much more fun they were having. She wanted to share her toys too, but she didn't know how.That's when a wise old owl appeared. The owl saw Sophie's struggle and asked her what was wrong. Sophie told the owl that she wanted to share her toys, but she didn't know how, and sometimes she found it hard to be patient and respectful towards others.The owl smiled and said, Patience, sharing, and respect are the keys, my dear Sophie. You need to be willing to wait your turn, be respectful towards others, and be happy when others play with your toys. This will make your friendships stronger and more meaningful.Sophie was confused, but she decided to take the owl's advice. She chose her favorite toy, a stuffed bunny, and gave it to her friend to play with. Sophie felt a little nervous at first, but when she saw how happy her friend was, she felt happy too.From that day on, Sophie tried to share her toys more often. She realized that sharing made her feel good and that it made her friendships stronger. She also found that her friends were more willing to share their toys with her when she shared hers with them.Whenever Sophie felt like she didn't want to share, or wasn't being patient or respectful, she remembered the wise old owl's words and took a deep breath. She knew that patience, sharing, and respect were important values to have.And so, Sophie lived happily ever after, playing with her friends, sharing her toys with them, and treating everyone with patience and respect. She learned that patience, sharing, and respect were the keys to having fun and making friendships stronger."),
            
            promtModel(age: 4,trait: "Respect,Sharing,", story: "Once upon a time, in a peaceful village, there lived a little boy named Ben. Ben loved to play and have fun, but sometimes he found it hard to share his toys and be respectful towards others.One day, Ben was playing at the park when he saw a little girl sitting all alone. Ben felt sorry for the girl and went over to see if she wanted to play. The girl was shy at first, but Ben's kindness made her feel more comfortable.Ben and the little girl started to play together, and they had a great time. But as they were playing, Ben noticed that the girl was looking at his toy car. Ben didn't want to share his toy car because he thought it was the best one.That's when a wise old owl appeared. The owl saw Ben's struggle and asked him what was wrong. Ben told the owl that he wanted to be respectful and share his toys, but sometimes it was hard.The owl smiled and said, Sharing and respect are the keys, my dear Ben. You need to be respectful towards others, no matter how different they are, and share your toys with them. This will make them feel appreciated and valued.Ben was confused, but he decided to take the owl's advice. He went over to the little girl and asked if she wanted to play with his toy car. The little girl was happy and started to play with the car.Ben felt good inside, knowing that he had done the right thing. He realized that sharing and respect were important values to have, and they made him feel good inside.From that day on, Ben tried to share his toys more often and treat everyone with respect. He realized that being respectful towards others made them feel valued and that sharing made his friendships stronger.Whenever Ben felt like he didn't want to share or wasn't being respectful, he remembered the wise old owl's words and took a deep breath. He knew that sharing and respect were important values to have.And so, Ben lived happily ever after, playing with his friends, sharing his toys with them, and treating everyone with respect. He learned that sharing and respect were the keys to having fun and making friendships stronger."),
            
        ]
    }
}
